version: '3.1'
services:
  redis:
    container_name: redis7002
    image: redis:5.0.6
    ports:
    - "7002:7002"
    - "17002:17002"
    volumes:
    - ./conf:/usr/local/etc/redis
    - ./data:/data
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
    - "redis-net"
networks:
  redis-net:
    external: true