apiVersion: v1 #api定义的版本
kind: Service #对象是service
metadata:
  name: redis-cluster-7000 #对象名字
  namespace: us-micro-dream-redis         #对象所处的命名空间
  labels:               #对象所拥有的标签
    redis-cluster-7000: redis-cluster-7000
spec:
  type: NodePort        #service类型，这里是NodePort，因为我需要本地用navicat去连k8s中的mysql，也就是我需要通过外网去访问集群内部的服务
  ports:
  - port: 7000          #service端口，集群内部访问的端口。（比如lumen .env中mysql的端口配置填的就是3306）
    targetPort: 7000    #这个是容器的端口，mysql pod定义的，对应就行
    nodePort: 7000     #这个是集群外部访问 mysql service的端口，也就是本地的navicat中填的端口连接信息
  - port: 17000          #service端口，集群内部访问的端口。（比如lumen .env中mysql的端口配置填的就是3306）
    targetPort: 17000    #这个是容器的端口，mysql pod定义的，对应就行
  selector:             #定义一下，service是需要匹配什么标签找到pod
    redis-cluster-7000: redis-cluster-7000